<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Información básica del proyecto -->
    <groupId>org.eon.wmsos</groupId>
    <artifactId>lst-api</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>OpenAPI Definition</name>
    <description>Proyecto que contiene la definición OpenAPI</description>

    <properties>
        <micronaut.openapi.generate.server>true</micronaut.openapi.generate.server>
        <micronaut.version>4.8.2</micronaut.version> <!-- Define la versión de Micronaut -->
    </properties>

    <!-- Dependencias (opcional) -->
    <dependencies>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server-netty</artifactId>
            <version>${micronaut.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject</artifactId>
            <version>${micronaut.version}</version>
        </dependency>        
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version> 
          </dependency>          
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.17.0</version> 
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.6.4</version> <!-- O una versión compatible con tu stack -->
        </dependency>
                          
        <!-- Otras dependencias necesarias -->
        <!--dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.4</version>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator-cli</artifactId>
            <version>6.6.0</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.1.10</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-models</artifactId>
            <version>2.1.10</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut.openapi</groupId>
            <artifactId>micronaut-openapi</artifactId>
            <version>${micronaut.version}</version>
        </dependency-->

    </dependencies>


    <!-- Configuración de recursos -->
    <build>
        <resources>
            <resource>
                <directory>api</directory>
                <targetPath>api</targetPath>
                <includes>
                    <include>**/*.yaml</include>
                </includes>
            </resource>
        </resources>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version> <!-- Usa la versión más reciente del plugin -->
                <configuration>
                    <source>17</source> <!-- Versión de Java para el código fuente -->
                    <target>17</target> <!-- Versión de Java para el bytecode generado -->
                    <release>17</release> <!-- Opcional: Especifica la versión de Java -->
                </configuration>
            </plugin>

            <!-- Plugin para generar clases a partir de OpenAPI -->
            <!--plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!- Directorio donde se generará el código ->
                            <outputDir>${project.build.directory}/generated-sources/openapi</outputDir>

                            <!- Generador para Spring Boot ->
                            <generatorName>spring</generatorName>

                            <!- Especificación OpenAPI (archivo YAML) ->
                            <inputSpec>${project.basedir}/api/lstock/openapi.yaml</inputSpec>

                            <!- Opciones de configuración ->
                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <modelPackage>org.eon.wmsos.model</modelPackage>
                                <apiPackage>org.eon.wmsos.api</apiPackage>
                                <invokerPackage>org.eon.wmsos.invoker</invokerPackage>
                                <library>spring-boot</library>
                                <useTags>true</useTags> <!- Usa tags para agrupar endpoints ->
                                <delegatePattern>true</delegatePattern> <!- Habilita patrón delegado ->
                                <generateApis>true</generateApis> <!- Genera controladores ->
                                <generateModels>true</generateModels> <!- Genera modelos ->
                                <generateSupportingFiles>false</generateSupportingFiles> <!- No genera archivos de soporte ->
                                <generateApiDocumentation>true</generateApiDocumentation> <!- Genera Javadoc para APIs ->
                                <generateModelDocumentation>true</generateModelDocumentation> <!- Genera Javadoc para modelos ->
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin-->

            <!-- Plugin para incluir las fuentes generadas en el compilador -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/openapi/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>io.micronaut.maven</groupId>
                <artifactId>micronaut-maven-plugin</artifactId>
                <version>${micronaut.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-openapi-server</goal>
                        </goals>
                        <configuration>
                            <definitionFile>api/wmsos/lst/openapi.yaml</definitionFile>
                            <outputDir>${project.build.directory}/generated-sources/openapi</outputDir>
                            <generatorName>micronaut</generatorName>
                            <apiPackageName>org.eon.wmsos.generated.api</apiPackageName>
                            <modelPackageName>org.eon.wmsos.generated.model</modelPackageName>
                            <invokerPackageName>org.eon.wmsos.generated.invoker</invokerPackageName>
                            <serializationFramework>jackson</serializationFramework>
                            <verbose>true</verbose>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>

</project>