{
    "type": "record",
    "name": "EvtStockOperation",
    "namespace": "org.eon.wmsos.events.stock.v1",
    "fields": [
        {
            "name": "created_at",
            "type": {
                "type": "long",
                "logicalType": "timestamp-micros"
            }
        },
        {
            "name": "operation",
            "type": "string"
        },
        {
            "name": "operationContent",
            "type": {
                "type": "array",
                "items": {
                    "type": "record",
                    "name": "OperationContent",
                    "fields": [
                        {
                            "name": "position",
                            "type": {
                                "type": "record",
                                "name": "EvtStockPosition",
                                "fields": [
                                    {
                                        "name": "id",
                                        "type": "string"
                                    },
                                    {
                                        "name": "metadata",
                                        "type": {
                                            "type": "array",
                                            "items": {
                                                "type": "record",
                                                "name": "EvtStockPositionMetadata",
                                                "fields": [
                                                    {
                                                        "name": "partialId",
                                                        "type": "string"
                                                    },
                                                    {
                                                        "name": "type",
                                                        "type": "string"
                                                    },
                                                    {
                                                        "name": "subtype",
                                                        "type": "string"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "name": "locationState",
                            "type": "string"
                        },
                        {
                            "name": "deltas",
                            "type": {
                                "type": "array",
                                "items": {
                                    "type": "record",
                                    "name": "EvtStockInfo",
                                    "fields": [
                                        {
                                            "name": "sku",
                                            "type": "string"
                                        },
                                        {
                                            "name": "amounts",
                                            "type": {
                                                "type": "array",
                                                "items": {
                                                    "type": "record",
                                                    "name": "EvtStockAmount",
                                                    "fields": [
                                                        {
                                                            "name": "state",
                                                            "type": "string"
                                                        },
                                                        {
                                                            "name": "amount",
                                                            "type": "int"
                                                        }
                                                    ]
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    ]
                }
            }
        }
    ]
}